### ISSUE TITLE
Problem: Current CDM cannot reflect accurately actions taken on intellectual entities

### ISSUE THREAD

**Issue by kellyannewithane** [JiscRDSS/Canonical-data-model#135]
preservationEventType vocabulary is based on PREMIS 2.0 which does not allow for events to be applied to intellectual entities (1 or more files which together form an intellectual whole - like a dataset).   

In order to be able to publish a preservation results message that indicates if the package was created we need to add PREMIS 3.0 eventTypes to the enumeration.  After that we can base a message on the eventType ['information package creation'](http://id.loc.gov/vocabulary/preservation/eventType/ipc.html)

**Comment by DomFripp** [comment]
So am I right in assuming that to also make this work, the preservationEvent entity needs to linked to the object level as well as file?

**Comment by jhsimpson** [comment]
Yes, in order to report that a dataset is preserved, we are talking about
publishing an 'information package creation's preservation event for the
dataset.  This event would include the identifier for the AIP that was
produced.

**Comment by DomFripp** [comment]
Solved by the implementation of the `informationPackage` model. https://github.com/JiscRDSS/Canonical-data-model/tree/master/Data-Model/Information-Package
